### ISSUE TITLE
Wonko needs sidedness for libraries, mods and other resources

### ISSUE THREAD

**Issue by peterix** [MultiMC/WonkoTheSane#2]
See #1 for previous discussion.

**Comment by 02JanDal** [comment]
From discussion on IRC: Possible solution: Split `"data"` into `"client"`, `"server"` etc. Could also add a `"common"` to reduce data duplication, in which case the values in `"client"`/`"server"` would overwrite resources in common.

**Comment by 02JanDal** [comment]
Another idea: `"<resource>-<side>"`. If a key for the wanted side is available, it's used, otherwise `"<resource>"` will be the fallback.

**Comment by robotbrain** [comment]
Need checksum for server libs

**Comment by 02JanDal** [comment]
Solved through extending `rules`
